### ISSUE TITLE
Unable to publish artifact to github package repository

### ISSUE THREAD

**Issue by christophfroeschl** [freefair/gradle-plugins#50] opened 2019-07-16 05:59 UTC
Using the github repository plugin I am able to publish the pom file but get http 400 responses for .jar and source artifacts.
Any idea what I'm doing wrong here?

```
> Task :publishMavenPublicationToGitHub *** Maven PackagesRepository
Could not transfer artifact io.myplant:commons:jar:4.0.3 from/to remote (https://maven.pkg.github.com/***): Could not write to resource '***/commons/4.0.3/commons-4.0.3.jar'
Could not transfer artifact io.myplant:commons:pom:4.0.3 from/to remote (https://maven.pkg.github.com/***): Could not write to resource '***/commons/4.0.3/commons-4.0.3.pom'
Could not transfer artifact io.myplant:commons:jar:sources:4.0.3 from/to remote (https://maven.pkg.github.com/***): Could not write to resource '***/commons/4.0.3/commons-4.0.3-sources.jar'

...

* What went wrong:
Execution failed for task ':publishMavenPublicationToGitHub *** Maven PackagesRepository'.
> Failed to publish publication 'maven' to repository 'GitHub *** Maven Packages'
   > Could not write to resource 'https://maven.pkg.github.com/***/***/commons/4.0.3/commons-4.0.3.jar'.
      > Could not PUT 'https://maven.pkg.github.com/***/***/commons/4.0.3/commons-4.0.3.jar'. Received status code 400 from server: Bad Request
```

**Comment by larsgrefer** [comment] 2019-07-16 09:13
Have you been accepted for the beta?

**Comment by christophfroeschl** [comment] 2019-07-16 10:40
yes

**Comment by larsgrefer** [comment] 2019-07-16 14:14
Lucky you. I havn't been acceppted yet, therefore I can't reproduce the problem.

Could you re-run the task with `--stracktrace`? Maybe this gives more information about the problem.

Also make sure to configure

```gradle
github {
    slug = "org/repo"
    username = "christophfroeschl"
    token = "yourSecretToken"
}
```

in your build.gradle

**Comment by DarthRevanXX** [comment] 2019-08-02 08:10
tried with Gradle and have no error but didn't publish it GitHub package repository.

> Task :wrapper

BUILD SUCCESSFUL in 243ms
1 actionable task: 1 executed
> Task :publishAllPublicationsToGitHub org Maven PackagesRepository UP-TO-DATE

BUILD SUCCESSFUL in 120ms

**Comment by larsgrefer** [comment] 2019-08-02 10:46
@DarthRevanXX It seems like your project doesn't have any publications to publish.

**Comment by madhead** [comment] 2019-08-03 23:35
I've noticed, that for a Maven publishing like this:

```kotlin
publishing {
    publications {
        create<MavenPublication>("main") {
            groupId = "by.dev.madhead.playgrounds"
            artifactId = "so57323260"
            version = "2.0.0"

            from(components["java"])
        }
    }
}
``` 

The plugin tries to execute the requests like this:

```bash
> Task :publishMainPublicationToGitHub madhead Maven PackagesRepository FAILED
Could not transfer artifact by.dev.madhead.playgrounds:so57323260:jar:2.0.0 from/to remote (https://maven.pkg.github.com/madhead): Could not write to resource 'by/dev/madhead/playgrounds/so57323260/2.0.0/so57323260-2.0.0.jar'
Could not transfer artifact by.dev.madhead.playgrounds:so57323260:pom:2.0.0 from/to remote (https://maven.pkg.github.com/madhead): Could not write to resource 'by/dev/madhead/playgrounds/so57323260/2.0.0/so57323260-2.0.0.pom'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMainPublicationToGitHub madhead Maven PackagesRepository'.
> Failed to publish publication 'main' to repository 'GitHub madhead Maven Packages'
   > Could not write to resource 'https://maven.pkg.github.com/madhead/by/dev/madhead/playgrounds/so57323260/2.0.0/so57323260-2.0.0.jar'.
      > Could not PUT 'https://maven.pkg.github.com/madhead/by/dev/madhead/playgrounds/so57323260/2.0.0/so57323260-2.0.0.jar'. Received status code 400 from server: Bad Request
```

Notice where it tries to put the JAR: `https://maven.pkg.github.com/madhead/by/dev/madhead/playgrounds/so57323260/2.0.0/so57323260-2.0.0.jar` That seems to be wrong, as it should look like `https://maven.pkg.github.com/madhead/<REPONAME>/so57323260/2.0.0/so57323260-2.0.0.jar`. I managed to push the package only when I've changed the publication:

```kotlin
publishing {
    publications {
        create<MavenPublication>("main") {
            groupId = "so57323260"
            artifactId = "so57323260""
            version = "2.0.0"

            from(components["java"])
        }
    }
}
```

Now the requests go to `madhead/so57323260` sub-URL, which is correct. Though, it doesn't seem like a good Maven `groupId`. Probably you should name your repository accordingly.

**Comment by larsgrefer** [comment] 2019-08-03 23:44
@madhead Thanks for the detailed investigation. Lets try this

**Comment by larsgrefer** [comment] 2019-08-04 00:39
@madhead @christophfroeschl Could you try it again with version `3.8.2` of the gradle plugin?

**Comment by DarthRevanXX** [comment] 2019-08-05 06:15
`AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenPublicationToGitHub test Maven PackagesRepository'.
> Failed to publish publication 'maven' to repository 'GitHub test Maven Packages'
   > java.net.URISyntaxException: Illegal character in path at index 43: https://maven.pkg.github.com/property(class java.lang.String, provider(?))

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s`

added publishing block, trying to run but have an error, on line 155 in "DefaultMavenArtifactRepository.java" failing to work

**Comment by DarthRevanXX** [comment] 2019-08-05 06:57
on 3.8.1 its publish but have an error
`Could not transfer metadata r10-jwk:r10-jwk-library/maven-metadata.xml from/to remote (https://maven.pkg.github.com/testlabs): Could not get resource 'r10-jwk/r10-jwk-library/maven-metadata.xml'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenPublicationToGitHub testlabs Maven PackagesRepository'.
> Failed to publish publication 'maven' to repository 'GitHub testlabs Maven Packages'
   > Could not GET 'https://maven.pkg.github.com/testlabs/r10-jwk/r10-jwk-library/maven-metadata.xml'. Received status code 422 from server: Unprocessable Entity

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
4 actionable tasks: 3 executed, 1 up-to-date
Cause: invalid type code: A0`

**Comment by madhead** [comment] 2019-08-05 08:51
3.8.2:

```shell
> Task :publishMainPublicationToGitHub madhead Maven PackagesRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMainPublicationToGitHub madhead Maven PackagesRepository'.
> Failed to publish publication 'main' to repository 'GitHub madhead Maven Packages'
   > java.net.URISyntaxException: Illegal character in path at index 43: https://maven.pkg.github.com/property(class java.lang.String, provider(?))

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':publishMainPublicationToGitHub madhead Maven PackagesRepository'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:138)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.artifacts.PublishException: Failed to publish publication 'main' to repository 'GitHub madhead Maven Packages'
        at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:38)
        at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.doPublish(PublishToMavenRepository.java:85)
        at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.publish(PublishToMavenRepository.java:73)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:401)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:390)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:373)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:79)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:210)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:117)
        ... 35 more
Caused by: org.gradle.api.UncheckedIOException: java.net.URISyntaxException: Illegal character in path at index 43: https://maven.pkg.github.com/property(class java.lang.String, provider(?))
        at org.gradle.api.internal.file.FileOrUriNotationConverter.convertToUrl(FileOrUriNotationConverter.java:126)
        at org.gradle.api.internal.file.FileOrUriNotationConverter.convert(FileOrUriNotationConverter.java:101)
        at org.gradle.internal.typeconversion.NotationConverterToNotationParserAdapter.parseNotation(NotationConverterToNotationParserAdapter.java:30)
        at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:47)
        at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToURI(AbstractFileResolver.java:97)
        at org.gradle.api.internal.file.AbstractFileResolver.resolveUri(AbstractFileResolver.java:90)
        at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.getUrl(DefaultMavenArtifactRepository.java:155)
        at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated.getUrl(Unknown Source)
        at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher.publish(AbstractMavenPublisher.java:40)
        at org.gradle.api.publish.maven.internal.publisher.StaticLockingMavenPublisher.publish(StaticLockingMavenPublisher.java:38)
        at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:49)
        at org.gradle.api.publish.maven.tasks.PublishToMavenRepository$1.publish(PublishToMavenRepository.java:83)
        at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:36)
        ... 89 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 43: https://maven.pkg.github.com/property(class java.lang.String, provider(?))
        at org.gradle.api.internal.file.FileOrUriNotationConverter.convertToUrl(FileOrUriNotationConverter.java:124)
        ... 101 more


* Get more help at https://help.gradle.org

BUILD FAILED in 1s
6 actionable tasks: 6 executed
```

**Comment by madhead** [comment] 2019-08-05 08:53
BTW, you can find the sources I'm trying with here: https://github.com/madhead/so57323260.

I run it like `./gradlew clean publish -PgithubUsername=madhead -PgithubToken=<token> --stacktrace`

**Comment by larsgrefer** [comment] 2019-08-05 09:04
> `java.net.URISyntaxException: Illegal character in path at index 43: https://maven.pkg.github.com/property(class java.lang.String, provider(?))`

This one was definitely my fault. Version `3.8.3` is currently beeing built and should be available soon for you to try again.

**Comment by DarthRevanXX** [comment] 2019-08-06 06:53
in other project have the error "Could not find any public constructor for class io.freefair.gradle.plugins.github.GithubExtension_Decorated which accepts parameters []."

**Comment by larsgrefer** [comment] 2019-09-07 23:38
I've been accepted for the beta in the meantime and successfully uploaded a packge with this plugin, so I'm closing this issue.

If you still have problems feel free to open another issue.

**Closed by larsgrefer** 2019-09-07 23:38 UTC
Labels: bug
